rm ../src/comn/*.o
rm ../src/gfit/*.o
rm ../src/ak/*.o
rm ../src/dayav/*.o
rm ../src/create_sunrun/caltech_ifs2/*.o
rm ../src/create_sunrun/lauder/*.o
rm ../src/create_sunrun/lamont_ifs3/*.o
rm ../src/create_sunrun/kitt_peak/*.o
rm ../src/create_sunrun/spit/*.o
rm ../src/create_sunrun/caltech_ifs1/*.o
rm ../src/create_sunrun/caltech_ifs3/*.o
rm ../src/create_sunrun/darwin_ifs2/*.o
rm ../src/create_sunrun/ftuvs_giessen/*.o
rm ../src/create_sunrun/parkfalls_ifs1/*.o
rm ../src/gggavg/*.o
rm ../src/create_runlog/*.o
rm ../src/vll/*.o
rm ../src/gsetup/*.o
rm ../src/extract_pth/*.o
rm ../src/ss2ames/*.o
rm ../src/bin2asc/*.o
