#!/bin/bash

if [ $# -lt 2 ]; then
    echo "Usage: diff_versions new_directory old_directory"
    echo "Example: ./diff_versions current_results benchmark_results"
    exit 0
fi

echo " Displaying compiler information:" > differences.out
echo " " >> differences.out
cat $GGGPATH/install/.compiler_ggg >> differences.out
echo " " >> differences.out
compiler=`head -n1 $GGGPATH/install/.compiler_ggg | awk -F= '{print $2}'`
`echo "$compiler --version"` >> differences.out


osname=`uname -s`
echo "The operating system is $osname. The details are: " >> differences.out
echo " " >> differences.out
if [ $osname == "Linux" ]
then
lsb_release -a >> differences.out
elif [ $osname == "Darwin" ]
then
sw_vers -productVersion >> differences.out
else
echo "Unknown version." >> differences.out
fi
echo " " >> differences.out


echo " "
echo " Computing and displaying any differences from the benchmark installation"
cat differences.i2s.out >> differences.out
echo " " >> differences.out
echo "--------------------------------" >> differences.out
echo " " >> differences.out
diff --brief --new-file $1/pa_ggg_benchmark.mav $2/pa_ggg_benchmark.mav >> differences.out
diff --brief --new-file $1/pa_ggg_benchmark.ray $2/pa_ggg_benchmark.ray >> differences.out
diff --brief --new-file $1/pa_ggg_benchmark.vav $2/pa_ggg_benchmark.vav >> differences.out
diff --brief --new-file $1/pa_ggg_benchmark.vsw $2/pa_ggg_benchmark.vsw >> differences.out
echo " "
ls -lt differences.out
echo " "
echo "Ensure that the magnitudes of the differences of important parameters (like Xgas, VSF_gas) "
echo "in the 'differences.out' file are smaller than ~0.01% to guarantee a successfull install. "
echo "Don't worry if the differences in S-G or non-target gas VSFs are larger than 0.01%."

echo "Check difference between "$1"/pa_ggg_benchmark.mav and "$2"/pa_ggg_benchmark.mav" >> differences.out
./ggg_mav_diff.pl $1/pa_ggg_benchmark.mav $2/pa_ggg_benchmark.mav >> differences.out
echo "Check difference between "$1"/pa_ggg_benchmark.ray and "$2"/pa_ggg_benchmark.ray" >> differences.out
./gggdiff.pl $1/pa_ggg_benchmark.ray $2/pa_ggg_benchmark.ray >> differences.out
echo "Check difference between "$1"/pa_ggg_benchmark.vav and "$2"/pa_ggg_benchmark.vav" >> differences.out
./gggdiff.pl $1/pa_ggg_benchmark.vav $2/pa_ggg_benchmark.vav >> differences.out
echo "Check difference between "$1"/pa_ggg_benchmark.vsw and "$2"/pa_ggg_benchmark.vsw" >> differences.out
./gggdiff.pl $1/pa_ggg_benchmark.vsw $2/pa_ggg_benchmark.vsw >> differences.out
echo "Check difference between "$1"/pa_ggg_benchmark.vav.ada.aia.oof and "$2"/pa_ggg_benchmark.vav.ada.aia.oof" >> differences.out
./gggdiff_oof.pl $1/pa_ggg_benchmark.vav.ada.aia.oof $2/pa_ggg_benchmark.vav.ada.aia.oof >> differences.out
echo "Check difference between "$1"/pa20040721_20041222.private.nc and "$2"/pa20040721_20041222.private.nc" >> differences.out
# note: order reversed from others
../bin/compare_netcdf $2/pa20040721_20041222.private.nc $1/pa20040721_20041222.private.nc >> differences.out 2>&1
